openapi: "3.0.0"
info:
  description: "Hello World Api"
  version: "1.0.0"
  title: "Civic API"
tags:
  - name: Hello
    description: Hello World
servers:
  - url: http://localhost:8080/v1
    description: "localhost"


#############################################################
# PATHS #####################################################
#############################################################

paths:
  /user:
    post:
      tags:
        - Person
      summary: "Add a User"
      operationId: "addUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addUserRequest'
      responses:
        201:
          description: "added"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addUserResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/Exception'

  /user/{userId}:
    get:
      tags:
        - User
      summary: "Gets a user"
      operationId: "getUser"
      parameters:
        - name: userId
          in: path
          description: "The primary key for the user you'd like to retrieve."
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Returns a user."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/Exception'

  /help:
    post:
      tags:
        - Help
      summary: "Add a Help"
      operationId: "addHelp"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addHelpRequest'
      responses:
        201:
          description: "added"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addHelpResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/Exception'

  /help/{helpId}:
    get:
      tags:
        - User
      summary: "Gets a help"
      operationId: "getHelp"
      parameters:
        - name: helpId
          in: path
          description: "The primary key for the help you'd like to retrieve."
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Returns a help."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/help'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/Exception'

  /helps:
    get:
      tags:
        - User
      summary: "Gets a list of helps"
      operationId: "getHelps"
      parameters:
        - name: userId
          in: query
          description: "The user id of the user that submitted the helps you'd like to retrieve."
          required: false
          schema:
            type: string
        - name: completed
          in: query
          description: "Indicates whether you would the results to include completed or incomplete. Send True/False. Do not include if you do not want to filter on this field."
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: "Returns all matching helps."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/helpsResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/Exception'

components:

  #############################################################
  # SCHEMAs ###################################################
  #############################################################

  schemas:

    #############################################################
    # DTOs ######################################################
    #############################################################

    user:
      type: object
      properties:
        userId:
            type: string
            example: "19ba06d2-629f-11eb-ae93-0242ac130002"
            description: "UUID that identifies a user."
        firstName:
          type: string
          example: "Jake"
          description: "Description of firstName"
        email:
          type: string
          example: "joesmith1234@gmail.com"
          description: "The email address associated to the user."
        lastName:
          type: string
          example: "Omaits"
          description: "Description of lastName"
        phone:
          type: string
          example: "7242731234"
        zip:
          type: string
          example: "15108"
        points:
          type: integer
          example: 33
        organizationId:
            type: string
            description: "UUID that identifies the org of which this user is a member. For future use, this may need to be changed to Many:1 but will remain 1:1, for now."

    addUserRequest:
      type: object
      properties:
        firstName:
          type: string
          example: "Jake"
          description: "Description of firstName"
        lastName:
          type: string
          example: "Omaits"
          description: "Description of lastName"
        email:
          type: string
          example: "joesmith1234@gmail.com"
          description: "The email address associated to the user."
        phone:
          type: string
          example: "7242731234"
        zip:
          type: string
          example: "15108"
        organizationId:
          type: string
          example: "19ba06d2-629f-11eb-ae93-0242ac130002"
          description: "UUID that identifies the org of which this user is a member. For future use, this may need to be changed to Many:1 but will remain 1:1, for now."
        password:
          type: string
          description: "The password used to login the user. This value will not be returned on GET operations."
          example: "Birr"

    addUserResponse:
      type: object
      properties:
        userId:
          type: string
          example: "19ba06d2-629f-11eb-ae93-0242ac130002"
          description: "UUID that identifies a user."

    help:
      type: object
      properties:
        helpId:
          type: string
          example: "19ba06d2-629f-11eb-ae93-0242ac130002"
          description: "UUID that identifies a help."
        userId:
          type: string
          example: "19ba06d2-629f-11eb-ae93-0242ac130002"
          description: "UUID that identifies a user."
        title:
          type: string
          example: "My cat is stuck in a tree."
          description: "Title of the help you need."
        description:
          type: string
          example: "It is a full grown bengal tiger. Please bring a tranq gun."
          description: "Description of help you need."
        zip:
          type: string
          example: "15108"
          description: "The zip code that corresponds to the location of the help."
        requestedDate:
          type: string
          example: "2020-01-30"
          description: "The date in which this help should be completed."
        helpType:
          type: string
          example: "Home Repair"
          description: "The type of help being requested."
        imageUrl:
          type: string
          description: "An image that can help the volunteers understand what needs done."
          example: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.meowingtons.com%2Fblogs%2Flolcats%2Fwhy-cats-get-stuck-in-trees-and-what-to-do-when-it-happens&psig=AOvVaw2HGr6-eWflr4L6EW5UJIxk&ust=1612119678737000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPjGiP6rxO4CFQAAAAAdAAAAABAD"
        timeOfDay:
            type: string
            description: "Free text field providing info on when the task could be completed."
            example: "Morning"
        daysRemaining:
            type: integer
            description: "Number of days left to complete this help. This field is calculated from the requested date minus current date."
            example: "5"
        completeDate:
            type: string
            description: "The date that the request was completed."
            example: "2020-01-10"
        comments:
            type: string
            description: "Freetext input from requester about the user that completed the help."
            example: "Jake was great. He really helped me out."
        completedBy:
            type: string
            description: "The ID of the person that completed this help."
            example: "b6ab3c46-62a3-11eb-ae93-0242ac130066"
        cheerMessage:
            type: string
            description: "The message to show under the accomplished card."
            example: "You and (2) others send cheers!"
        cheered:
            type: string
            description: "Indicates if the current user has cheered this help."
            example: "True"

    helpsResponse:
        type: object
        description: "Collection of helps that meet the specified search criteria."
        properties:
          helps:
            type: array
            items:
              $ref: '#/components/schemas/help'

    addHelpRequest:
      type: object
      properties:
        userId:
          type: string
          example: "19ba06d2-629f-11eb-ae93-0242ac130002"
          description: "UUID that identifies a user."
        title:
          type: string
          example: "My cat is stuck in a tree."
          description: "Title of the help you need."
        description:
          type: string
          example: "It is a full grown bengal tiger. Please bring a tranq gun."
          description: "Description of help you need."
        zip:
          type: string
          example: "15108"
          description: "The zip code that corresponds to the location of the help."
        requestedDate:
          type: string
          format: date
          example: "2020-01-30"
          description: "The date in which this help should be completed."
        helpType:
          type: string
          example: "Home Repair"
          description: "The type of help being requested."
        imageUrl:
          type: string
          description: "An image that can help the volunteers understand what needs done."
          example: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.meowingtons.com%2Fblogs%2Flolcats%2Fwhy-cats-get-stuck-in-trees-and-what-to-do-when-it-happens&psig=AOvVaw2HGr6-eWflr4L6EW5UJIxk&ust=1612119678737000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPjGiP6rxO4CFQAAAAAdAAAAABAD"
          format: uri
        timeOfDay:
          type: string
          description: "Free text field providing info on when the task could be completed."
          example: "Morning"

    addHelpResponse:
      type: object
      properties:
        helpId:
          type: string
          example: "19ba06d2-629f-11eb-ae93-0242ac130002"
          description: "UUID that identifies the request."

    organization:
        type: object
        properties:
            organizationId:
              type: string
              example: "19ba06d2-629f-11eb-ae93-0242ac130002"
              description: "UUID that identifies an organization."
            description:
              type: string
              description: "The name of the organization"
              example: "Coraoplis Church of Christ"


  #############################################################
  #todo: build out more comprehensive list of status codes and descriptions
  #############################################################
  responses:
    NotFound:
      description: The specified resource was not found.
    Unauthorized:
      description: You are not authorized to access this resource.
    Exception:
      description: A system error has occurred and the request was not processed.
    Created:
      description: The request was processed successfully and the resource has been created.
    BadRequest:
      description: The request could not be understood by the server due to malformed data.
    NotAllowed:
      description: The server has not implemented the requested HTTP method.
    OK:
      description: The request has processed successfully.