server:
  address: 0.0.0.0
  port: ${PORT:8080}
info:
  component: civic-api

logging:
  level:
    root: info

spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:adyen-tender-api}
    username: sa
  h2:
    console:
      enabled: true
